name: Feature Request
description: Suggest an idea for Amorsize
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please fill out the form below.
  
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm always frustrated when...
    validations:
      required: true
  
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: I would like Amorsize to...
    validations:
      required: true
  
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe alternatives you've considered
      placeholder: I've thought about...
  
  - type: textarea
    id: example
    attributes:
      label: Example Usage
      description: Provide an example of how you'd use this feature
      render: python
      placeholder: |
        from amorsize import new_feature
        
        result = new_feature(...)
  
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Nice to have
        - Important
        - Critical
    validations:
      required: true
  
  - type: checkboxes
    id: related
    attributes:
      label: Related Areas
      description: Which areas of Amorsize does this feature relate to?
      options:
        - label: Core optimization logic
        - label: System information detection
        - label: API design
        - label: Performance benchmarking
        - label: Documentation
        - label: CLI interface
        - label: Configuration management
  
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request here
